server:
  servlet:
    context-path: /envisu4-tools
  port: 8080
  forward-headers-strategy: framework
logging:
  level:
    root: INFO
application:
  ipol:
    endpoint: ${IPOL_ENDPOINT:https://ipolcore.ipol.im}
    demo_id: ${IPOL_DEMO_ID:77777000125}
  animatedgif:
    delay: ${DEFAULT_DELAY:500}
  notification:
    slack: ${SLACK_URL:}
  actuator:
    user: ${ACTUATOR_USER:actuator}
    #password is generate with GeneratePassword class default is "actuator"
    passwd: ${ACTUATOR_PASSWORD:{bcrypt}$2a$10$haLsRQkZdhF1FtzV4iXFi.MiPOlDKN.i4FaWrjitA3eDFwoWeuMa2}
         
spring:
  application:
    name: envisu4-tools
  datasource:
    url: ${MYSQL_URL_ENV:jdbc:mysql://localhost:3318/envisu4?serverTimezone=CET&useSSL=false}
    username: ${MYSQL_USER:dev1}
    password: ${MYSQL_PASSWD:dev1}
  jpa:
    hibernate.ddl-auto : update
    hibernate.use-new-id-generator-mappings : false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000KB
      location: ${java.io.tmpdir} 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FUSIONAUTH_ISSUER:weverify.eu}
          jwk-set-uri: ${FUSIONAUTH_URL:http://localhost:9011}/.well-known/jwks.json

  
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - health
        - info
        - loggers
      base-path: /manage
      
  endpoint:
    health:
      enabled: true
      show-details: when-authorized
      show-components: when-authorized
    info:
      enabled: true
    loggers:
      enabled: true            
---
server:
  servlet:
    context-path: /
spring:
  profiles: prod 
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false